version: "3"
services:
  alpha:
    container_name: alpha
    #image: alpha
    build: 
      context: ./alpha
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    hostname: alpha
    ports:
      - 8080:80
  beta:
    container_name: beta
    #image: beta
    build: 
      context: ./beta
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    hostname: beta
    ports:
      - 8081:80
  nginx:
    container_name: nginx
    #image: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - beta
      - alpha
    ports:
      - 9000:80

  mariadb:
    image: mariadb
      volumes:
        - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
