version: "3"
services:
  alpha:
    container_name: alpha
    build: 
      context: ./alpha
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    hostname: alpha
    ports:
      - "8080:80"
    volumes:
          - ./app1:/var/www/html/
  beta:
    container_name: beta
    build: 
      context: ./beta
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    hostname: beta
    ports:
      - "8081:80"
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9000:80
    depends_on:
      - beta
      - alpha
  mariadb:
    image: mariadb
      volumes:
        - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
